language: python
python:
- '2.6'
- '2.7'
- '3.3'
- 3.2
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- nightly
- pypy
- pypy3

env: TOXENV=py

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.2
  - python: 3.7-dev
  - python: nightly
  - python: pypy
  - python: pypy3
  include:
  - python: 3.2
    env: TOXENV=py32

cache: python
install: pip install -e file://`pwd`#egg=tox
script: tox
