language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- nightly
- pypy

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.7-dev
  - python: nightly
  - python: pypy
cache: python
install: pip install tox
script: tox -e py

deploy:
  provider: pypi
  on:
    tags: true
    python: 3.6
  user: hpk
  password:
    secure: <encrypted_password> <!--otherwise use api_key-->
  distributions: sdist bdist_wheel
  skip_upload_docs: true
